# Generated by Django 6.0.4 on 2026-04-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ALUNO', 'Aluno'), ('SERVIDOR', 'Servidor'), ('GESTOR', 'Gestor'), ('ADM', 'Administrador')], default='ALUNO', max_length=10),
        ),
    ]
