# Generated by Django 6.0.4 on 2026-04-20 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usuario_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('ELETRICA', 'Elétrica'), ('HIDRAULICA', 'Hidráulica'), ('BARULHO', 'Barulho'), ('SEGURANCA', 'Segurança')], max_length=20)),
                ('descricao', models.TextField()),
                ('urgente', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='reclamacoes/fotos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='reclamacoes/videos/')),
                ('status', models.CharField(default='Pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
