# Generated by Django 6.0.4 on 2026-04-20 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bloco_quarto_alocacao_solicitacaotroca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DENUNCIA', 'Denúncia Anônima'), ('COMPORTAMENTO', 'Comportamento Inadequado'), ('PERDA', 'Perda de Chave/Cartão')], max_length=20)),
                ('descricao', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
