# Generated by Django 6.0.4 on 2026-04-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cidade_curso_alter_usuario_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamacao',
            name='data_fim_reparo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamacao',
            name='data_inicio_reparo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamacao',
            name='foto_depois',
            field=models.ImageField(blank=True, null=True, upload_to='reparos/depois/'),
        ),
        migrations.AddField(
            model_name='reclamacao',
            name='oto_antes',
            field=models.ImageField(blank=True, null=True, upload_to='reparos/antes/'),
        ),
    ]
