# Generated by Django 6.0.4 on 2026-04-21 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_reclamacao_data_fim_reparo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitante_nome', models.CharField(blank=True, max_length=100, null=True)),
                ('visitante_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VistoriaQuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('cama_organizada', models.BooleanField(default=False)),
                ('danos', models.BooleanField(default=False)),
                ('limpeza', models.BooleanField(default=False)),
                ('itens_proibidos', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('foto_vistoria', models.ImageField(blank=True, null=True, upload_to='vistorias/')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quarto')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
