# Generated by Django 6.0.4 on 2026-05-25 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_registroacesso_vistoriaquarto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustoFixoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField(help_text='Insira o primeiro dia do mês correspondente (ex: 01/05/2026)')),
                ('consumo_agua', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumo_luz', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='alocacao',
            name='data_alocacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='quarto_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.quarto'),
        ),
        migrations.AddField(
            model_name='quarto',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo / Disponível'), ('REFORMA', 'Interditado para Reforma')], default='ATIVO', max_length=15),
        ),
        migrations.AddField(
            model_name='reclamacao',
            name='custo_reparo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reclamacao',
            name='servidor_atendente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='aprovado_gestor',
            field=models.BooleanField(default=False, help_text='Define se o servidor foi validado pelo gestor.'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='bloqueado',
            field=models.BooleanField(default=False, help_text='Indica se o usuário está suspenso do alojamento.'),
        ),
        migrations.CreateModel(
            name='AdvertenciaDisciplinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('gravidade', models.CharField(choices=[('LEVE', 'Leve'), ('MEDIA', 'Média'), ('GRAVE', 'Grave')], default='LEVE', max_length=10)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertencias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
