# Generated by Django 6.0.4 on 2026-06-01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_custofixomensal_alocacao_data_alocacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamacao',
            old_name='oto_antes',
            new_name='foto_antes',
        ),
    ]
